### ISSUE TITLE
Add Mac support

### ISSUE THREAD

**Issue by cwensley** [clicketyclackety/Crash#13]
**Describe the bug**
Currently Crash! only supports Windows.  We should also add support for Mac.  Unfortunately, since mono does not appear to support WebSockets this will likely only be able to be done for v8 WIP.

**Comment by clicketyclackety** [comment]
I think fully supporting mac, even if it's only Rhino 8 WIP and onwards would be a fantastic achievement. It'd allow for cross platform model sharing. I'm not aware of a cad package that supports that currently.

Since Rhinos geometry kernel is pretty stable and consistent I don't envision that there would be any issues transferring between versions

**Comment by fraguada** [comment]
I was able to test this on Rhino 8 WIP for Mac and was sort of working. Notes:

- Please create a package for mac. At the moment, no mac uses can see this in the package manager. To install it I had to go to the yak listing for the package, download the yak file, switch .yak to .macrhi, and drag and drop it into R8.
- Users on windows were not able to see my changes, but I was also not able to see some users changes. I was also on a VPN, so this might have affected my connection performance. I did see a few names and some geometry!
- Consider that the `ActiveDoc` can change in mac, as Rhino for Mac is multi document. You target ActiveDoc in several places: https://github.com/clicketyclackety/Crash/search?q=activedoc For that matter, consider what happens when a user on Windows starts a new file. You might want to listen to the [CloseDocument](https://developer.rhino3d.com/api/RhinoCommon/html/E_Rhino_RhinoDoc_CloseDocument.htm) event.

**Comment by clicketyclackety** [comment]
@fraguada, thanks for these pointers. I will create a PR to fix as many of these issues as possible 😊
